version: "3" #version of docker-compose(MUST BE ADDED TO AVOID ERROR)
services:
  #Postgres Container config
  postgres:
    #services- name(postgres)
    container_name: postgres-sql
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api_courses
    # volumes:
    #   - postgres:/var/lib/postgresql/data
    networks:
      - spring-boot-network

  # Spring Boot App Container config
  spring-boot:
    #services- name(spring-boot)
    container_name: spring-boot
    # build: .
    image: spring/rest-mvc
    ports:
      - "8080:8080"
    networks:
      - spring-boot-network
      # environment:
      # - SPRING_PROFILES_ACTIVE=dev
      # - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/api_courses
      # - SPRING_DATASOURCE_USERNAME=postgres
      # - SPRING_DATASOURCE_PASSWORD=password

    depends_on:
      - postgres

networks:
  spring-boot-network:
    driver: bridge

volumes:
  postgres:
